### ISSUE TITLE
Unusual behaviour of BiMap updateKeyAt() and updateValueAt() functions

### ISSUE THREAD

**Issue by st-clair-clarke** [rimbu-org/rimbu#101]
## Environment

OS: Linux Cinnamon
Node: v16.13.0
Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)
 

## Reproduction

```
import { BiMap } from '@rimbu/core'

const biMap: BiMap<number, number> = BiMap.of<number, number>([1, 2], [3, 4])
const biMapPrompt = `💲biMap = BiMap.of<number, number>([1, 2], [3, 4])`

console.log(biMap.updateKeyAt(2, 10).toArray())

{
  console.log(`\n🟡 Update...`)
  {
    console.log(`🔵 updateKeyAt()`)
    console.log(`${biMapPrompt}`)
    console.log(`💲▶️ biMap.updateKeyAt(1, 11).toArray() ✅👉️`, biMap.updateKeyAt(1, 11).toArray())
    console.log(
      `💲▶️ biMap.updateKeyAt(3, value => value + 1).toArray() ✅👉️`,
      biMap.updateKeyAt(3, value => value + 1).toArray()
    )
    console.log(`💲▶️ biMap.updateKeyAt(6, 20).toArray() ✅👉️`, biMap.updateKeyAt(6, 20).toArray())
  }

  {
    console.log(`\n🔵 updateValueAt()`)
    console.log(`${biMapPrompt}`)
    console.log(`💲▶️ biMap.updateValueAt(2, 22).toArray() ✅👉️`, biMap.updateValueAt(2, 22).toArray())
    console.log(
      `💲▶️ biMap.updateValueAt(4, value => value + 1).toArray() ✅👉️`,
      biMap.updateValueAt(4, value => value + 1).toArray()
    )
    console.log(`💲▶️ biMap.updateValueAt(6, 20).toArray() ✅👉️`, biMap.updateValueAt(6, 20).toArray())
  }
}
```

![image](https://user-images.githubusercontent.com/3227590/189765910-c03b25a7-2bb4-485d-921c-78ff693fd952.png)

## Steps to reproduce
Simply paste the reproduction code in an IDE and run the file

## Actual Behavior

Neither key nor value is being updated

## The first console statement prints the correct output to the console output❗❗
Why the other statement are not updating is unusual.
This is the only function on BiMap that I have encountered an error and I have reproduce all properties and function outputs as per the documentation

**Comment by vitoke** [comment]
Thanks for taking the time to report your findings.

There may be some confusion regarding the names of the `updateKeyAt` and `updateValueAt` functions. I find it hard to come up with a good name for them, but it may be that they do exactly the opposite from what you expect. They should be read as:

* `updateValueAt(key, value)`: update the value associated with given key X
* `updateKeyAt(value, key)`: update the key associated with given value X

Because the keys and values in your example are the same number type, the compiler will not complain. If, for example, it would have been a `BiMap<number, string>`, then you can call `updateKeyAt('a', 5)` and `updateValueAt(5, 'a')`.

I think in your example, if you switch around `updateKeyAt` and `updateValueAt`, it will behave more like you expect.

Let me know if this solves the problem. Also, any suggestions for better names are welcome.

**Comment by st-clair-clarke** [comment]
You are correct - I misinterpreted the key and value parameter placement. Generally, I think of a function with key and value as 

```
f(key, value)
```
...and hence used that in my interpretation that was erroneus. After your explanation, everything worked out fine. But to make the functions more intuitive, I have the following suggestions

## Rename

```
updateValueAtKey(key, newValue): update the value associated with given 'key' to 'newValue'.
updateKeyAtValue(newKey, value): update the 'key'  associated with given 'value' to  'newKey'

``

## Not the function parameters are in the form (key, value) for both functions with a more explicit function name.

Let me know what you think.

**Comment by vitoke** [comment]
I think the longer names are a good idea, the bidirectional nature of the BiMap makes things somewhat confusing.

I also get that the `updateKeyAtValue` order of arguments is counterintuitive. Having the fixed order does mean that you can have something like `updateKeyAtValue(v => v + 1, 'a')`. I need to figure out if I like that order. I'll decide before the next release.

**Comment by vitoke** [comment]
I've changed the names and also the parameter order as you suggested. Your argument for consistency in parameter order convinced me, so thanks. The Pull Request will close this issue.

**Comment by st-clair-clarke** [comment]
Saw the final lib. Great!
