### ISSUE TITLE
Regarding @rimbu/deep match() latest version

### ISSUE THREAD

**Issue by st-clair-clarke** [rimbu-org/rimbu#109]
## Arrays and Tuples

```
// compound matches
const result = match(
  [
    { x: 1, y: 2 },
    { x: 3, y: 0 },
  ],
  { some: [{ x: (v) => v > 5 }, { y: (v) => v < 2 }] }
)

console.log(result) // false
```

The example suggests that the return value should be **true**

### Function Matchers

```
match(
  {
    a: 1,
    b: { c: 2, d: { e: 3 } },
  },
  {
    b: {
      d: { e: (value, parent, root) => value === parent.c + root.a },
    },
  }
); // => true

// instead of returning the boolean in the previous statement, it is also possible to directly match the value
match(
  {
    a: 1,
    b: { c: 2, d: { e: 3 } },
  },
  {
    b: {
      d: { e: (value, parent, root) => parent.c + root.a },
    },
  }
); // => true
```

Both matchers actually return **false** for me.

**Comment by vitoke** [comment]
Indeed, something seems to be off there, thanks for submitting. I remember reading about a plugin that can run documentation examples, I should look into that.
I'll investigate the cause.

**Comment by st-clair-clarke** [comment]
The documentation is excellent as is - just being diligent before I commit using the lib in my project.

**Comment by vitoke** [comment]
Rightfully so. The examples were incorrect, I updated them so that they should work. I also took the opportunity to add more array matching features, including array traversal matchers (see the new docs). I should Probably freeze the API for now, it's now possible to write crazy complex and powerful matchers. Not that anyone necessarily should do that though.
